
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

logoFile="logo.png"

credits="VoidArkana(Coder and artist), Psalidodont(Main artist), Dino Tazz Arts (artist), Ninni (Music), Messy Slimey (Music)"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="4.4,"
    ordering="BEFORE"
    side="BOTH"